name: C++ CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            conan-config: default
            conan-target: release
          - os: ubuntu-latest
            conan-target: release
            conan-config: release
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Conan
        run: pip install conan==2.* cmake

      - name: Cache Conan dependencies
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ${{ runner.os == 'windows-latest' && 'C:\\Users\\runneradmin\\.conan2' || '/home/runner/.conan2' }}
          key: conan-${{ runner.os }}-${{ hashFiles('**/conanfile.py') }}

      - name: Create default profile (if cache miss)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: conan profile detect --force

      - name: Install deps (Conan)
        run: conan install . --output-folder build --build=missing -s compiler.cppstd=20 -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True --deployer=full_deploy -o spdlog/*:header_only=True

      - name: Configure CMake
        run: cmake --preset conan-${{ matrix.conan-config }}

      - name: Build
        run: cmake --build --preset conan-${{ matrix.conan-target }} --config Release

      - name: Package Release
        shell: bash
        run: |
          mkdir -p dist/include
          cp -r include/* dist/include/

          # Copy dependencies headers
          find build/full_deploy -type d -name include | while read dir; do
            cp -rL "$dir"/. dist/include/
          done

          # Copy dependencies licenses
          find build/full_deploy -type f \( -iname "LICENSE*" -o -iname "COPYING*" -o -iname "Copyright*" \) | while read file; do
            rel_path="${file#build/full_deploy/}"
            mkdir -p "dist/licenses/$(dirname "$rel_path")"
            cp "$file" "dist/licenses/$rel_path"
          done

          if [ "${{ runner.os }}" == "Windows" ]; then
            # Copy dependencies binaries
            find build/full_deploy -type d -name bin | while read dir; do cp "$dir"/*.dll dist/ 2>/dev/null || : ; done
            find build/full_deploy -type d -name lib | while read dir; do cp "$dir"/*.lib dist/ 2>/dev/null || : ; done

            find build \( -name "*.exe" -o -name "*.lib" -o -name "*.dll" \) -not -path "*/CMakeFiles/*" -not -path "*/full_deploy/*" -exec cp {} dist/ \;
            cd dist && 7z a ../RoarEngine-Windows.zip *
          else
            # Copy dependencies binaries
            find build/full_deploy -type d -name lib | while read dir; do cp "$dir"/*.a dist/ 2>/dev/null || : ; done
            find build/full_deploy -type d -name lib | while read dir; do cp "$dir"/*.so dist/ 2>/dev/null || : ; done

            find build -type f -executable -not -path "*/CMakeFiles/*" -not -path "*/full_deploy/*" -not -name "CMake*" -not -name "*.cmake" -not -name "Makefile" -exec cp {} dist/ \;
            find build \( -name "*.a" -o -name "*.so" \) -not -path "*/CMakeFiles/*" -not -path "*/full_deploy/*" -exec cp {} dist/ \;
            cd dist && tar -czvf ../RoarEngine-Linux.tar.gz *
          fi

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RoarEngine-Windows.zip
            RoarEngine-Linux.tar.gz
